// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	// API 端访问令牌（`Authorization: Bearer <jwt>`）。.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleCookieAuth handles cookieAuth security.
	// Web 端 HTTP-only Cookie（`access-token` / `refresh-token`，`SameSite=Lax`）。.
	HandleCookieAuth(ctx context.Context, operationName OperationName, t CookieAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AddGroupMemberOperation:             []string{},
	AuthLogoutOperation:                 []string{},
	ChangeMyPasswordOperation:           []string{},
	CreateDataSourceOperation:           []string{},
	CreateEnvironmentOperation:          []string{},
	CreateExportTaskOperation:           []string{},
	CreateGroupOperation:                []string{},
	CreateIdentityProviderOperation:     []string{},
	CreateInstanceOperation:             []string{},
	CreateProjectOperation:              []string{},
	CreateUserOperation:                 []string{},
	CreateWorksheetOperation:            []string{},
	DeleteDataSourceOperation:           []string{},
	DeleteEnvironmentOperation:          []string{},
	DeleteGroupOperation:                []string{},
	DeleteIdentityProviderOperation:     []string{},
	DeleteInstanceOperation:             []string{},
	DeleteProjectOperation:              []string{},
	DeleteUserOperation:                 []string{},
	DeleteWorksheetOperation:            []string{},
	DownloadExportTaskOperation:         []string{},
	ExportAuditLogsOperation:            []string{},
	FavoriteWorksheetOperation:          []string{},
	GetDatabaseOperation:                []string{},
	GetEnvironmentPolicyOperation:       []string{},
	GetExportTaskOperation:              []string{},
	GetGroupOperation:                   []string{},
	GetIamPolicyOperation:               []string{},
	GetIdentityProviderOperation:        []string{},
	GetInstanceOperation:                []string{},
	GetProjectOperation:                 []string{},
	GetSettingOperation:                 []string{},
	GetUnreadNotificationCountOperation: []string{},
	GetUserOperation:                    []string{},
	GetWorksheetOperation:               []string{},
	ListDatabasesOperation:              []string{},
	ListExportTasksOperation:            []string{},
	ListGroupMembersOperation:           []string{},
	ListGroupsOperation:                 []string{},
	ListInstancesOperation:              []string{},
	ListMyFavoritesOperation:            []string{},
	ListMyNotificationsOperation:        []string{},
	ListProjectsOperation:               []string{},
	ListUsersOperation:                  []string{},
	MarkAllNotificationsReadOperation:   []string{},
	MarkNotificationReadOperation:       []string{},
	QueryHistoriesSearchOperation:       []string{},
	RegenerateMyMfaOperation:            []string{},
	RemoveGroupMemberOperation:          []string{},
	SearchAuditLogsOperation:            []string{},
	SearchWorksheetsOperation:           []string{},
	SetIamPolicyOperation:               []string{},
	SqlExportOperation:                  []string{},
	SqlQueryOperation:                   []string{},
	SyncDatabaseSchemaOperation:         []string{},
	SyncInstanceOperation:               []string{},
	TestIamPermissionsOperation:         []string{},
	TestIdentityProviderOperation:       []string{},
	TestInstanceConnectionOperation:     []string{},
	UndeleteProjectOperation:            []string{},
	UndeleteUserOperation:               []string{},
	UnfavoriteWorksheetOperation:        []string{},
	UpdateDataSourceOperation:           []string{},
	UpdateDatabaseOperation:             []string{},
	UpdateEnvironmentOperation:          []string{},
	UpdateEnvironmentPolicyOperation:    []string{},
	UpdateGroupOperation:                []string{},
	UpdateIdentityProviderOperation:     []string{},
	UpdateInstanceOperation:             []string{},
	UpdateProjectOperation:              []string{},
	UpdateSettingOperation:              []string{},
	UpdateUserOperation:                 []string{},
	UpdateWorksheetOperation:            []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesCookieAuth is a private map storing roles per operation.
var operationRolesCookieAuth = map[string][]string{
	AddGroupMemberOperation:             []string{},
	AuthLogoutOperation:                 []string{},
	ChangeMyPasswordOperation:           []string{},
	CreateDataSourceOperation:           []string{},
	CreateEnvironmentOperation:          []string{},
	CreateExportTaskOperation:           []string{},
	CreateGroupOperation:                []string{},
	CreateIdentityProviderOperation:     []string{},
	CreateInstanceOperation:             []string{},
	CreateProjectOperation:              []string{},
	CreateUserOperation:                 []string{},
	CreateWorksheetOperation:            []string{},
	DeleteDataSourceOperation:           []string{},
	DeleteEnvironmentOperation:          []string{},
	DeleteGroupOperation:                []string{},
	DeleteIdentityProviderOperation:     []string{},
	DeleteInstanceOperation:             []string{},
	DeleteProjectOperation:              []string{},
	DeleteUserOperation:                 []string{},
	DeleteWorksheetOperation:            []string{},
	DownloadExportTaskOperation:         []string{},
	ExportAuditLogsOperation:            []string{},
	FavoriteWorksheetOperation:          []string{},
	GetDatabaseOperation:                []string{},
	GetEnvironmentPolicyOperation:       []string{},
	GetExportTaskOperation:              []string{},
	GetGroupOperation:                   []string{},
	GetIamPolicyOperation:               []string{},
	GetIdentityProviderOperation:        []string{},
	GetInstanceOperation:                []string{},
	GetProjectOperation:                 []string{},
	GetSettingOperation:                 []string{},
	GetUnreadNotificationCountOperation: []string{},
	GetUserOperation:                    []string{},
	GetWorksheetOperation:               []string{},
	ListDatabasesOperation:              []string{},
	ListExportTasksOperation:            []string{},
	ListGroupMembersOperation:           []string{},
	ListGroupsOperation:                 []string{},
	ListInstancesOperation:              []string{},
	ListMyFavoritesOperation:            []string{},
	ListMyNotificationsOperation:        []string{},
	ListProjectsOperation:               []string{},
	ListUsersOperation:                  []string{},
	MarkAllNotificationsReadOperation:   []string{},
	MarkNotificationReadOperation:       []string{},
	QueryHistoriesSearchOperation:       []string{},
	RegenerateMyMfaOperation:            []string{},
	RemoveGroupMemberOperation:          []string{},
	SearchAuditLogsOperation:            []string{},
	SearchWorksheetsOperation:           []string{},
	SetIamPolicyOperation:               []string{},
	SqlExportOperation:                  []string{},
	SqlQueryOperation:                   []string{},
	SyncDatabaseSchemaOperation:         []string{},
	SyncInstanceOperation:               []string{},
	TestIamPermissionsOperation:         []string{},
	TestIdentityProviderOperation:       []string{},
	TestInstanceConnectionOperation:     []string{},
	UndeleteProjectOperation:            []string{},
	UndeleteUserOperation:               []string{},
	UnfavoriteWorksheetOperation:        []string{},
	UpdateDataSourceOperation:           []string{},
	UpdateDatabaseOperation:             []string{},
	UpdateEnvironmentOperation:          []string{},
	UpdateEnvironmentPolicyOperation:    []string{},
	UpdateGroupOperation:                []string{},
	UpdateIdentityProviderOperation:     []string{},
	UpdateInstanceOperation:             []string{},
	UpdateProjectOperation:              []string{},
	UpdateSettingOperation:              []string{},
	UpdateUserOperation:                 []string{},
	UpdateWorksheetOperation:            []string{},
}

// GetRolesForCookieAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForCookieAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForCookieAuth(operation string) []string {
	roles, ok := operationRolesCookieAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t CookieAuth
	const parameterName = "access-token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesCookieAuth[operationName]
	rctx, err := s.sec.HandleCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
