// Code generated by ogen, DO NOT EDIT.
package oas

type AddGroupMemberRes interface {
	addGroupMemberRes()
}

type AuthCsrfRes interface {
	authCsrfRes()
}

type AuthLoginRes interface {
	authLoginRes()
}

type AuthLogoutRes interface {
	authLogoutRes()
}

type AuthPasswordResetConfirmRes interface {
	authPasswordResetConfirmRes()
}

type AuthPasswordResetRequestRes interface {
	authPasswordResetRequestRes()
}

type AuthRefreshRes interface {
	authRefreshRes()
}

type ChangeMyPasswordRes interface {
	changeMyPasswordRes()
}

type CreateDataSourceRes interface {
	createDataSourceRes()
}

type CreateEnvironmentRes interface {
	createEnvironmentRes()
}

type CreateExportTaskRes interface {
	createExportTaskRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreateIdentityProviderRes interface {
	createIdentityProviderRes()
}

type CreateInstanceRes interface {
	createInstanceRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateUserRes interface {
	createUserRes()
}

type CreateWorksheetRes interface {
	createWorksheetRes()
}

type DeleteDataSourceRes interface {
	deleteDataSourceRes()
}

type DeleteEnvironmentRes interface {
	deleteEnvironmentRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteIdentityProviderRes interface {
	deleteIdentityProviderRes()
}

type DeleteInstanceRes interface {
	deleteInstanceRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type DeleteWorksheetRes interface {
	deleteWorksheetRes()
}

type DownloadExportTaskRes interface {
	downloadExportTaskRes()
}

type ExportAuditLogsRes interface {
	exportAuditLogsRes()
}

type FavoriteWorksheetRes interface {
	favoriteWorksheetRes()
}

type GetDatabaseRes interface {
	getDatabaseRes()
}

type GetEnvironmentPolicyRes interface {
	getEnvironmentPolicyRes()
}

type GetExportTaskRes interface {
	getExportTaskRes()
}

type GetGroupRes interface {
	getGroupRes()
}

type GetIamPolicyRes interface {
	getIamPolicyRes()
}

type GetIdentityProviderRes interface {
	getIdentityProviderRes()
}

type GetInstanceRes interface {
	getInstanceRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetSettingRes interface {
	getSettingRes()
}

type GetUnreadNotificationCountRes interface {
	getUnreadNotificationCountRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetWorksheetRes interface {
	getWorksheetRes()
}

type ListDatabasesRes interface {
	listDatabasesRes()
}

type ListEnvironmentsRes interface {
	listEnvironmentsRes()
}

type ListExportTasksRes interface {
	listExportTasksRes()
}

type ListGroupMembersRes interface {
	listGroupMembersRes()
}

type ListGroupsRes interface {
	listGroupsRes()
}

type ListIdentityProvidersRes interface {
	listIdentityProvidersRes()
}

type ListInstancesRes interface {
	listInstancesRes()
}

type ListMyFavoritesRes interface {
	listMyFavoritesRes()
}

type ListMyNotificationsRes interface {
	listMyNotificationsRes()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type MarkAllNotificationsReadRes interface {
	markAllNotificationsReadRes()
}

type MarkNotificationReadRes interface {
	markNotificationReadRes()
}

type QueryHistoriesSearchRes interface {
	queryHistoriesSearchRes()
}

type ReadyzRes interface {
	readyzRes()
}

type RegenerateMyMfaRes interface {
	regenerateMyMfaRes()
}

type RemoveGroupMemberRes interface {
	removeGroupMemberRes()
}

type SearchAuditLogsRes interface {
	searchAuditLogsRes()
}

type SearchWorksheetsRes interface {
	searchWorksheetsRes()
}

type SetIamPolicyRes interface {
	setIamPolicyRes()
}

type SqlExportRes interface {
	sqlExportRes()
}

type SqlQueryRes interface {
	sqlQueryRes()
}

type SyncDatabaseSchemaRes interface {
	syncDatabaseSchemaRes()
}

type SyncInstanceRes interface {
	syncInstanceRes()
}

type TestIamPermissionsRes interface {
	testIamPermissionsRes()
}

type TestIdentityProviderRes interface {
	testIdentityProviderRes()
}

type TestInstanceConnectionRes interface {
	testInstanceConnectionRes()
}

type UndeleteProjectRes interface {
	undeleteProjectRes()
}

type UndeleteUserRes interface {
	undeleteUserRes()
}

type UnfavoriteWorksheetRes interface {
	unfavoriteWorksheetRes()
}

type UpdateDataSourceRes interface {
	updateDataSourceRes()
}

type UpdateDatabaseRes interface {
	updateDatabaseRes()
}

type UpdateEnvironmentPolicyRes interface {
	updateEnvironmentPolicyRes()
}

type UpdateEnvironmentRes interface {
	updateEnvironmentRes()
}

type UpdateGroupRes interface {
	updateGroupRes()
}

type UpdateIdentityProviderRes interface {
	updateIdentityProviderRes()
}

type UpdateInstanceRes interface {
	updateInstanceRes()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UpdateSettingRes interface {
	updateSettingRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UpdateWorksheetRes interface {
	updateWorksheetRes()
}
