// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddGroupMember implements addGroupMember operation.
	//
	// 添加组成员.
	//
	// POST /v1/groups/{group}/members
	AddGroupMember(ctx context.Context, req *AddGroupMemberRequest, params AddGroupMemberParams) (AddGroupMemberRes, error)
	// AuthCsrf implements authCsrf operation.
	//
	// Cookie 写操作采用双提交 CSRF：首屏由此下发 `X-CSRF-Token`， 后续 POST/PATCH/DELETE
	// 请求头回传。纯 Bearer 调用不受 CSRF 影响。.
	//
	// GET /v1/auth/csrf
	AuthCsrf(ctx context.Context) (AuthCsrfRes, error)
	// AuthLogin implements authLogin operation.
	//
	// 邮箱密码登录；若该账号开启 MFA，返回 `mfa_temp_token`（access_token 为空），
	// 需再次以 `mfa_temp_token` + `otp_code`/`recovery_code` 完成二次验证。
	// 失败按锁定窗口计数（密码 10/10min、MFA 5/5min，见 14-F）。.
	//
	// POST /v1/auth:login
	AuthLogin(ctx context.Context, req *LoginRequest, params AuthLoginParams) (AuthLoginRes, error)
	// AuthLogout implements authLogout operation.
	//
	// 吊销当前 refresh token / 会话。.
	//
	// POST /v1/auth:logout
	AuthLogout(ctx context.Context) (AuthLogoutRes, error)
	// AuthPasswordResetConfirm implements authPasswordResetConfirm operation.
	//
	// 以重置凭证 + 新密码完成修改，校验新密码强度。.
	//
	// POST /v1/auth:passwordReset:confirm
	AuthPasswordResetConfirm(ctx context.Context, req *PasswordResetConfirmRequest) (AuthPasswordResetConfirmRes, error)
	// AuthPasswordResetRequest implements authPasswordResetRequest operation.
	//
	// 校验邮箱存在性后下发重置凭证（实现选定通道，v1 站内/邮件自定）。.
	//
	// POST /v1/auth:passwordReset:request
	AuthPasswordResetRequest(ctx context.Context, req *PasswordResetRequest) (AuthPasswordResetRequestRes, error)
	// AuthRefresh implements authRefresh operation.
	//
	// 以 refresh token 换取新的 access token。.
	//
	// POST /v1/auth:refresh
	AuthRefresh(ctx context.Context, req *RefreshRequest) (AuthRefreshRes, error)
	// ChangeMyPassword implements changeMyPassword operation.
	//
	// 校验旧密码 + 新密码强度（自身改密，按归属判定）。.
	//
	// POST /v1/users/me:password
	ChangeMyPassword(ctx context.Context, req *ChangePasswordRequest, params ChangeMyPasswordParams) (ChangeMyPasswordRes, error)
	// CreateDataSource implements createDataSource operation.
	//
	// 实例下数据源，资源名段 `{dataSource}`
	// 即角色（`admin`/`readonly`，每实例各至多一个）。 POST 为 upsert
	// 语义（按角色键覆盖）。凭据加密存储（D25）。.
	//
	// POST /v1/projects/{project}/instances/{instance}/dataSources/{dataSource}
	CreateDataSource(ctx context.Context, req *DataSource, params CreateDataSourceParams) (CreateDataSourceRes, error)
	// CreateEnvironment implements createEnvironment operation.
	//
	// 仅 workspaceAdmin/securityAdmin。.
	//
	// POST /v1/environments/{environment}
	CreateEnvironment(ctx context.Context, req *Environment, params CreateEnvironmentParams) (CreateEnvironmentRes, error)
	// CreateExportTask implements createExportTask operation.
	//
	// 异步导出大结果集；幂等创建支持请求头 `X-Request-Id`。
	// 任务完成后向发起人推站内通知（`export_done`）。.
	//
	// POST /v1/projects/{project}/exportTasks
	CreateExportTask(ctx context.Context, req *CreateExportTaskRequest, params CreateExportTaskParams) (CreateExportTaskRes, error)
	// CreateGroup implements createGroup operation.
	//
	// 创建用户组.
	//
	// POST /v1/groups
	CreateGroup(ctx context.Context, req *Group, params CreateGroupParams) (CreateGroupRes, error)
	// CreateIdentityProvider implements createIdentityProvider operation.
	//
	// 创建 IdP（按 name upsert）.
	//
	// POST /v1/identityProviders/{idp}
	CreateIdentityProvider(ctx context.Context, req *IdentityProvider, params CreateIdentityProviderParams) (CreateIdentityProviderRes, error)
	// CreateInstance implements createInstance operation.
	//
	// 在项目内注册一个数据库实例；必须标注环境。支持
	// `validate_only`（测试连接，不落库）。.
	//
	// POST /v1/projects/{project}/instances
	CreateInstance(ctx context.Context, req *CreateInstanceRequest, params CreateInstanceParams) (CreateInstanceRes, error)
	// CreateProject implements createProject operation.
	//
	// 仅 workspaceAdmin（D1/D15）。.
	//
	// POST /v1/projects
	CreateProject(ctx context.Context, req *CreateProjectRequest, params CreateProjectParams) (CreateProjectRes, error)
	// CreateUser implements createUser operation.
	//
	// 仅 workspaceAdmin。kind=user。.
	//
	// POST /v1/users
	CreateUser(ctx context.Context, req *CreateUserRequest, params CreateUserParams) (CreateUserRes, error)
	// CreateWorksheet implements createWorksheet operation.
	//
	// 保存的查询；可见性 PRIVATE/PROJECT（分享只传递 SQL 文本，D18/D36）。.
	//
	// POST /v1/projects/{project}/worksheets
	CreateWorksheet(ctx context.Context, req *Worksheet, params CreateWorksheetParams) (CreateWorksheetRes, error)
	// DeleteDataSource implements deleteDataSource operation.
	//
	// 删除数据源.
	//
	// DELETE /v1/projects/{project}/instances/{instance}/dataSources/{dataSource}
	DeleteDataSource(ctx context.Context, params DeleteDataSourceParams) (DeleteDataSourceRes, error)
	// DeleteEnvironment implements deleteEnvironment operation.
	//
	// 被实例引用时阻塞（409）。.
	//
	// DELETE /v1/environments/{environment}
	DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (DeleteEnvironmentRes, error)
	// DeleteGroup implements deleteGroup operation.
	//
	// 历史 IAM 绑定 `group:x@` 保留（永不命中，D31）。.
	//
	// DELETE /v1/groups/{group}
	DeleteGroup(ctx context.Context, params DeleteGroupParams) (DeleteGroupRes, error)
	// DeleteIdentityProvider implements deleteIdentityProvider operation.
	//
	// 删除 IdP.
	//
	// DELETE /v1/identityProviders/{idp}
	DeleteIdentityProvider(ctx context.Context, params DeleteIdentityProviderParams) (DeleteIdentityProviderRes, error)
	// DeleteInstance implements deleteInstance operation.
	//
	// 删除实例（软删）.
	//
	// DELETE /v1/projects/{project}/instances/{instance}
	DeleteInstance(ctx context.Context, params DeleteInstanceParams) (DeleteInstanceRes, error)
	// DeleteProject implements deleteProject operation.
	//
	// 非空阻塞；显式 `force=true` 才级联软删（D27）。.
	//
	// DELETE /v1/projects/{project}
	DeleteProject(ctx context.Context, params DeleteProjectParams) (DeleteProjectRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// 默认禁用（status=disabled）；worksheet 保留为孤儿（creator 标已禁用）。.
	//
	// DELETE /v1/users/{user}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// DeleteWorksheet implements deleteWorksheet operation.
	//
	// 删除 Worksheet（soft）.
	//
	// DELETE /v1/projects/{project}/worksheets/{worksheet}
	DeleteWorksheet(ctx context.Context, params DeleteWorksheetParams) (DeleteWorksheetRes, error)
	// DownloadExportTask implements downloadExportTask operation.
	//
	// 校验用户自设 ZIP 密码；错误 → `403 EXPORT_PASSWORD_INVALID`。 产物过期已清理
	// → `404 EXPORT_ARCHIVE_EXPIRED`。下载流式解密下发。.
	//
	// POST /v1/projects/{project}/exportTasks/{task}:download
	DownloadExportTask(ctx context.Context, req *DownloadExportRequest, params DownloadExportTaskParams) (DownloadExportTaskRes, error)
	// ExportAuditLogs implements exportAuditLogs operation.
	//
	// 按检索条件导出（CSV/JSON），返回字节流。审计的审计（x-audit:true）。.
	//
	// POST /v1/auditLogs:export
	ExportAuditLogs(ctx context.Context, req *SearchAuditLogsRequest, params ExportAuditLogsParams) (ExportAuditLogsRes, error)
	// FavoriteWorksheet implements favoriteWorksheet operation.
	//
	// 收藏 Worksheet.
	//
	// POST /v1/projects/{project}/worksheets/{worksheet}:favorite
	FavoriteWorksheet(ctx context.Context, params FavoriteWorksheetParams) (FavoriteWorksheetRes, error)
	// GetDatabase implements getDatabase operation.
	//
	// 含 `effective_environment`（数据库未显式标注环境时继承实例环境）。.
	//
	// GET /v1/projects/{project}/instances/{instance}/databases/{database}
	GetDatabase(ctx context.Context, params GetDatabaseParams) (GetDatabaseRes, error)
	// GetEnvironmentPolicy implements getEnvironmentPolicy operation.
	//
	// 查询/导出护栏（行数上限等运行时策略）。.
	//
	// GET /v1/environments/{environment}/policy
	GetEnvironmentPolicy(ctx context.Context, params GetEnvironmentPolicyParams) (GetEnvironmentPolicyRes, error)
	// GetExportTask implements getExportTask operation.
	//
	// 查询任务状态、行数、产物引用等。.
	//
	// GET /v1/projects/{project}/exportTasks/{task}
	GetExportTask(ctx context.Context, params GetExportTaskParams) (GetExportTaskRes, error)
	// GetGroup implements getGroup operation.
	//
	// 获取用户组.
	//
	// GET /v1/groups/{group}
	GetGroup(ctx context.Context, params GetGroupParams) (GetGroupRes, error)
	// GetIamPolicy implements getIamPolicy operation.
	//
	// 作用于任意资源（`projects/{p}` 或具体实例/库）。`resource`
	// 在请求体传递（资源名含 `/`）。 仅 v1 预置角色；绑定含结构化条件。.
	//
	// POST /v1/iam:getIamPolicy
	GetIamPolicy(ctx context.Context, req *GetIamPolicyRequest) (GetIamPolicyRes, error)
	// GetIdentityProvider implements getIdentityProvider operation.
	//
	// 获取 IdP.
	//
	// GET /v1/identityProviders/{idp}
	GetIdentityProvider(ctx context.Context, params GetIdentityProviderParams) (GetIdentityProviderRes, error)
	// GetInstance implements getInstance operation.
	//
	// 获取实例.
	//
	// GET /v1/projects/{project}/instances/{instance}
	GetInstance(ctx context.Context, params GetInstanceParams) (GetInstanceRes, error)
	// GetProject implements getProject operation.
	//
	// 获取项目.
	//
	// GET /v1/projects/{project}
	GetProject(ctx context.Context, params GetProjectParams) (GetProjectRes, error)
	// GetSetting implements getSetting operation.
	//
	// 读取平台设置.
	//
	// GET /v1/settings/{key}
	GetSetting(ctx context.Context, params GetSettingParams) (GetSettingRes, error)
	// GetUnreadNotificationCount implements getUnreadNotificationCount operation.
	//
	// 未读通知计数.
	//
	// GET /v1/users/me/notifications:unreadCount
	GetUnreadNotificationCount(ctx context.Context) (GetUnreadNotificationCountRes, error)
	// GetUser implements getUser operation.
	//
	// 获取用户.
	//
	// GET /v1/users/{user}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// GetWorksheet implements getWorksheet operation.
	//
	// 获取 Worksheet.
	//
	// GET /v1/projects/{project}/worksheets/{worksheet}
	GetWorksheet(ctx context.Context, params GetWorksheetParams) (GetWorksheetRes, error)
	// Healthz implements healthz operation.
	//
	// 进程存活探针，不做就绪判定，不依赖下游。.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzOK, error)
	// ListDatabases implements listDatabases operation.
	//
	// 返回实例内调用者可见的逻辑库（鉴权过滤）。.
	//
	// GET /v1/projects/{project}/instances/{instance}/databases
	ListDatabases(ctx context.Context, params ListDatabasesParams) (ListDatabasesRes, error)
	// ListEnvironments implements listEnvironments operation.
	//
	// 供前端渲染环境标签与策略下拉。.
	//
	// GET /v1/environments
	ListEnvironments(ctx context.Context) (ListEnvironmentsRes, error)
	// ListExportTasks implements listExportTasks operation.
	//
	// 返回项目内调用者可见的导出任务（鉴权过滤）。.
	//
	// GET /v1/projects/{project}/exportTasks
	ListExportTasks(ctx context.Context, params ListExportTasksParams) (ListExportTasksRes, error)
	// ListGroupMembers implements listGroupMembers operation.
	//
	// 列出组成员.
	//
	// GET /v1/groups/{group}/members
	ListGroupMembers(ctx context.Context, params ListGroupMembersParams) (ListGroupMembersRes, error)
	// ListGroups implements listGroups operation.
	//
	// 列出用户组.
	//
	// GET /v1/groups
	ListGroups(ctx context.Context, params ListGroupsParams) (ListGroupsRes, error)
	// ListIdentityProviders implements listIdentityProviders operation.
	//
	// 登录页渲染 SSO 按钮可匿名读取（仅返回 enabled +
	// title/type/domain，不含密钥）。.
	//
	// GET /v1/identityProviders
	ListIdentityProviders(ctx context.Context) (ListIdentityProvidersRes, error)
	// ListInstances implements listInstances operation.
	//
	// 返回项目内调用者可见的实例（鉴权过滤）。.
	//
	// GET /v1/projects/{project}/instances
	ListInstances(ctx context.Context, params ListInstancesParams) (ListInstancesRes, error)
	// ListMyFavorites implements listMyFavorites operation.
	//
	// 当前用户的收藏书签（指向 worksheet）。.
	//
	// GET /v1/users/me/favorites
	ListMyFavorites(ctx context.Context, params ListMyFavoritesParams) (ListMyFavoritesRes, error)
	// ListMyNotifications implements listMyNotifications operation.
	//
	// 我的站内通知.
	//
	// GET /v1/users/me/notifications
	ListMyNotifications(ctx context.Context, params ListMyNotificationsParams) (ListMyNotificationsRes, error)
	// ListProjects implements listProjects operation.
	//
	// 仅返回调用者所属项目（鉴权过滤；workspaceAdmin/securityAdmin 可见全部）。.
	//
	// GET /v1/projects
	ListProjects(ctx context.Context, params ListProjectsParams) (ListProjectsRes, error)
	// ListUsers implements listUsers operation.
	//
	// 列出用户.
	//
	// GET /v1/users
	ListUsers(ctx context.Context, params ListUsersParams) (ListUsersRes, error)
	// MarkAllNotificationsRead implements markAllNotificationsRead operation.
	//
	// 全部标记已读.
	//
	// POST /v1/users/me/notifications:markAllRead
	MarkAllNotificationsRead(ctx context.Context, params MarkAllNotificationsReadParams) (MarkAllNotificationsReadRes, error)
	// MarkNotificationRead implements markNotificationRead operation.
	//
	// 标记单条已读.
	//
	// POST /v1/users/me/notifications/{id}:markRead
	MarkNotificationRead(ctx context.Context, params MarkNotificationReadParams) (MarkNotificationReadRes, error)
	// QueryHistoriesSearch implements queryHistoriesSearch operation.
	//
	// 仅返回调用者本人的查询/导出历史（按归属判定，非 ACL）。.
	//
	// GET /v1/queryHistories:search
	QueryHistoriesSearch(ctx context.Context, params QueryHistoriesSearchParams) (QueryHistoriesSearchRes, error)
	// Readyz implements readyz operation.
	//
	// 校验平台元数据库连通性，可承接流量时返回 ready。.
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// RegenerateMyMfa implements regenerateMyMfa operation.
	//
	// 重新生成 TOTP secret（应用层加密）与恢复码，返回一次性置顶信息。.
	//
	// POST /v1/users/me:mfa:regenerate
	RegenerateMyMfa(ctx context.Context, params RegenerateMyMfaParams) (RegenerateMyMfaRes, error)
	// RemoveGroupMember implements removeGroupMember operation.
	//
	// 移除组成员.
	//
	// DELETE /v1/groups/{group}/members/{member}
	RemoveGroupMember(ctx context.Context, params RemoveGroupMemberParams) (RemoveGroupMemberRes, error)
	// SearchAuditLogs implements searchAuditLogs operation.
	//
	// 结构化过滤（method/user/resource/severity/create_time）。 `parent` = `projects/{p}`
	// 走项目级读权限（projectOwner 可读本项目，D26）； 省略 `parent`
	// 为全局（securityAdmin / workspaceAdmin）。大表分页上限 5000，可不返回 total_size。.
	//
	// POST /v1/auditLogs:search
	SearchAuditLogs(ctx context.Context, req *SearchAuditLogsRequest) (SearchAuditLogsRes, error)
	// SearchWorksheets implements searchWorksheets operation.
	//
	// 返回项目内调用者可见的 worksheet（可见性 + 归属）。.
	//
	// GET /v1/projects/{project}/worksheets:search
	SearchWorksheets(ctx context.Context, params SearchWorksheetsParams) (SearchWorksheetsRes, error)
	// SetIamPolicy implements setIamPolicy operation.
	//
	// 乐观锁：请求带 `etag`，服务端不匹配 → `409 CONCURRENT_MODIFICATION`。
	// 审计记录变更前后差异（service_data）。.
	//
	// POST /v1/iam:setIamPolicy
	SetIamPolicy(ctx context.Context, req *SetIamPolicyRequest, params SetIamPolicyParams) (SetIamPolicyRes, error)
	// SqlExport implements sqlExport operation.
	//
	// 小结果集同步导出，返回用户自设密码加密的 ZIP 字节流。 预估 >1
	// 万行（EXPLAIN 估算，见 D22）→ `412 EXPORT_TOO_LARGE_FOR_SYNC`，改走异步 ExportTask。.
	//
	// POST /v1/projects/{project}/instances/{instance}/databases/{database}:export
	SqlExport(ctx context.Context, req *ExportRequest, params SqlExportParams) (SqlExportRes, error)
	// SqlQuery implements sqlQuery operation.
	//
	// 核心查询路径。多语句（分号分隔）首请求执行全部语句，响应 `results[]`
	// 按序返回每条语句的首页； 取某结果集下一页 → 带 `page_token` 再次 POST
	// `:query`（此时 `statement` 忽略，服务端按 token 续读）。
	// 只读强制；语句超时、行数/字节上限按环境策略 `environment_policies` 生效。.
	//
	// POST /v1/projects/{project}/instances/{instance}/databases/{database}:query
	SqlQuery(ctx context.Context, req *QueryRequest, params SqlQueryParams) (SqlQueryRes, error)
	// SyncDatabaseSchema implements syncDatabaseSchema operation.
	//
	// 即时返回 202 + 当前 sync_status；后台异步反射 schema 写入快照（D41）。.
	//
	// POST /v1/projects/{project}/instances/{instance}/databases/{database}:syncSchema
	SyncDatabaseSchema(ctx context.Context, params SyncDatabaseSchemaParams) (SyncDatabaseSchemaRes, error)
	// SyncInstance implements syncInstance operation.
	//
	// 即时返回 202 + 当前 `sync_status` + 触发时间；后台异步执行（D41）。 完成后写
	// `last_sync_time`/`sync_status`，可选推站内通知。不引入 LRO 轮询。.
	//
	// POST /v1/projects/{project}/instances/{instance}:sync
	SyncInstance(ctx context.Context, params SyncInstanceParams) (SyncInstanceRes, error)
	// TestIamPermissions implements testIamPermissions operation.
	//
	// 按调用者本人对 `resource` 持有的权限判定，返回命中的权限子集（用于前端
	// UI 收敛）。.
	//
	// POST /v1/iam:testIamPermissions
	TestIamPermissions(ctx context.Context, req *TestIamPermissionsRequest) (TestIamPermissionsRes, error)
	// TestIdentityProvider implements testIdentityProvider operation.
	//
	// 以授权码测试连通性，返回 `IdentityProviderUserInfo`（不落库）。.
	//
	// POST /v1/identityProviders/{idp}:test
	TestIdentityProvider(ctx context.Context, req *TestIdentityProviderRequest, params TestIdentityProviderParams) (TestIdentityProviderRes, error)
	// TestInstanceConnection implements testInstanceConnection operation.
	//
	// 以请求体中的数据源凭据尝试连接（`validate_only` 语义），不落库。.
	//
	// POST /v1/projects/{project}/instances/{instance}:testConnection
	TestInstanceConnection(ctx context.Context, req *TestConnectionRequest, params TestInstanceConnectionParams) (TestInstanceConnectionRes, error)
	// UndeleteProject implements undeleteProject operation.
	//
	// 恢复已删除项目.
	//
	// POST /v1/projects/{project}:undelete
	UndeleteProject(ctx context.Context, params UndeleteProjectParams) (UndeleteProjectRes, error)
	// UndeleteUser implements undeleteUser operation.
	//
	// 恢复用户.
	//
	// POST /v1/users/{user}:undelete
	UndeleteUser(ctx context.Context, params UndeleteUserParams) (UndeleteUserRes, error)
	// UnfavoriteWorksheet implements unfavoriteWorksheet operation.
	//
	// 取消收藏 Worksheet.
	//
	// POST /v1/projects/{project}/worksheets/{worksheet}:unfavorite
	UnfavoriteWorksheet(ctx context.Context, params UnfavoriteWorksheetParams) (UnfavoriteWorksheetRes, error)
	// UpdateDataSource implements updateDataSource operation.
	//
	// 更新数据源.
	//
	// PATCH /v1/projects/{project}/instances/{instance}/dataSources/{dataSource}
	UpdateDataSource(ctx context.Context, req *DataSource, params UpdateDataSourceParams) (UpdateDataSourceRes, error)
	// UpdateDatabase implements updateDatabase operation.
	//
	// 更新数据库（标签/显示设置）.
	//
	// PATCH /v1/projects/{project}/instances/{instance}/databases/{database}
	UpdateDatabase(ctx context.Context, req *Database, params UpdateDatabaseParams) (UpdateDatabaseRes, error)
	// UpdateEnvironment implements updateEnvironment operation.
	//
	// 更新环境.
	//
	// PATCH /v1/environments/{environment}
	UpdateEnvironment(ctx context.Context, req *Environment, params UpdateEnvironmentParams) (UpdateEnvironmentRes, error)
	// UpdateEnvironmentPolicy implements updateEnvironmentPolicy operation.
	//
	// 仅 securityAdmin/workspaceAdmin；记审计前值。.
	//
	// PATCH /v1/environments/{environment}/policy
	UpdateEnvironmentPolicy(ctx context.Context, req *EnvironmentPolicy, params UpdateEnvironmentPolicyParams) (UpdateEnvironmentPolicyRes, error)
	// UpdateGroup implements updateGroup operation.
	//
	// 更新用户组.
	//
	// PATCH /v1/groups/{group}
	UpdateGroup(ctx context.Context, req *Group, params UpdateGroupParams) (UpdateGroupRes, error)
	// UpdateIdentityProvider implements updateIdentityProvider operation.
	//
	// 更新 IdP.
	//
	// PATCH /v1/identityProviders/{idp}
	UpdateIdentityProvider(ctx context.Context, req *IdentityProvider, params UpdateIdentityProviderParams) (UpdateIdentityProviderRes, error)
	// UpdateInstance implements updateInstance operation.
	//
	// PATCH + JSON Merge Patch；可改展示名、同步间隔、设置等。.
	//
	// PATCH /v1/projects/{project}/instances/{instance}
	UpdateInstance(ctx context.Context, req *Instance, params UpdateInstanceParams) (UpdateInstanceRes, error)
	// UpdateProject implements updateProject operation.
	//
	// 更新项目.
	//
	// PATCH /v1/projects/{project}
	UpdateProject(ctx context.Context, req *Project, params UpdateProjectParams) (UpdateProjectRes, error)
	// UpdateSetting implements updateSetting operation.
	//
	// 仅 workspaceAdmin/securityAdmin；记审计前值。.
	//
	// PATCH /v1/settings/{key}
	UpdateSetting(ctx context.Context, req *Setting, params UpdateSettingParams) (UpdateSettingRes, error)
	// UpdateUser implements updateUser operation.
	//
	// 更新用户.
	//
	// PATCH /v1/users/{user}
	UpdateUser(ctx context.Context, req *User, params UpdateUserParams) (UpdateUserRes, error)
	// UpdateWorksheet implements updateWorksheet operation.
	//
	// 乐观锁；`If-Match: <etag>`，不匹配 → `409 CONCURRENT_MODIFICATION`。.
	//
	// PATCH /v1/projects/{project}/worksheets/{worksheet}
	UpdateWorksheet(ctx context.Context, req *Worksheet, params UpdateWorksheetParams) (UpdateWorksheetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
