// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddGroupMember implements addGroupMember operation.
//
// 添加组成员.
//
// POST /v1/groups/{group}/members
func (UnimplementedHandler) AddGroupMember(ctx context.Context, req *AddGroupMemberRequest, params AddGroupMemberParams) (r AddGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthCsrf implements authCsrf operation.
//
// Cookie 写操作采用双提交 CSRF：首屏由此下发 `X-CSRF-Token`， 后续 POST/PATCH/DELETE
// 请求头回传。纯 Bearer 调用不受 CSRF 影响。.
//
// GET /v1/auth/csrf
func (UnimplementedHandler) AuthCsrf(ctx context.Context) (r AuthCsrfRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthLogin implements authLogin operation.
//
// 邮箱密码登录；若该账号开启 MFA，返回 `mfa_temp_token`（access_token 为空），
// 需再次以 `mfa_temp_token` + `otp_code`/`recovery_code` 完成二次验证。
// 失败按锁定窗口计数（密码 10/10min、MFA 5/5min，见 14-F）。.
//
// POST /v1/auth:login
func (UnimplementedHandler) AuthLogin(ctx context.Context, req *LoginRequest, params AuthLoginParams) (r AuthLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthLogout implements authLogout operation.
//
// 吊销当前 refresh token / 会话。.
//
// POST /v1/auth:logout
func (UnimplementedHandler) AuthLogout(ctx context.Context) (r AuthLogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthPasswordResetConfirm implements authPasswordResetConfirm operation.
//
// 以重置凭证 + 新密码完成修改，校验新密码强度。.
//
// POST /v1/auth:passwordReset:confirm
func (UnimplementedHandler) AuthPasswordResetConfirm(ctx context.Context, req *PasswordResetConfirmRequest) (r AuthPasswordResetConfirmRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthPasswordResetRequest implements authPasswordResetRequest operation.
//
// 校验邮箱存在性后下发重置凭证（实现选定通道，v1 站内/邮件自定）。.
//
// POST /v1/auth:passwordReset:request
func (UnimplementedHandler) AuthPasswordResetRequest(ctx context.Context, req *PasswordResetRequest) (r AuthPasswordResetRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthRefresh implements authRefresh operation.
//
// 以 refresh token 换取新的 access token。.
//
// POST /v1/auth:refresh
func (UnimplementedHandler) AuthRefresh(ctx context.Context, req *RefreshRequest) (r AuthRefreshRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangeMyPassword implements changeMyPassword operation.
//
// 校验旧密码 + 新密码强度（自身改密，按归属判定）。.
//
// POST /v1/users/me:password
func (UnimplementedHandler) ChangeMyPassword(ctx context.Context, req *ChangePasswordRequest, params ChangeMyPasswordParams) (r ChangeMyPasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDataSource implements createDataSource operation.
//
// 实例下数据源，资源名段 `{dataSource}`
// 即角色（`admin`/`readonly`，每实例各至多一个）。 POST 为 upsert
// 语义（按角色键覆盖）。凭据加密存储（D25）。.
//
// POST /v1/projects/{project}/instances/{instance}/dataSources/{dataSource}
func (UnimplementedHandler) CreateDataSource(ctx context.Context, req *DataSource, params CreateDataSourceParams) (r CreateDataSourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEnvironment implements createEnvironment operation.
//
// 仅 workspaceAdmin/securityAdmin。.
//
// POST /v1/environments/{environment}
func (UnimplementedHandler) CreateEnvironment(ctx context.Context, req *Environment, params CreateEnvironmentParams) (r CreateEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateExportTask implements createExportTask operation.
//
// 异步导出大结果集；幂等创建支持请求头 `X-Request-Id`。
// 任务完成后向发起人推站内通知（`export_done`）。.
//
// POST /v1/projects/{project}/exportTasks
func (UnimplementedHandler) CreateExportTask(ctx context.Context, req *CreateExportTaskRequest, params CreateExportTaskParams) (r CreateExportTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGroup implements createGroup operation.
//
// 创建用户组.
//
// POST /v1/groups
func (UnimplementedHandler) CreateGroup(ctx context.Context, req *Group, params CreateGroupParams) (r CreateGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateIdentityProvider implements createIdentityProvider operation.
//
// 创建 IdP（按 name upsert）.
//
// POST /v1/identityProviders/{idp}
func (UnimplementedHandler) CreateIdentityProvider(ctx context.Context, req *IdentityProvider, params CreateIdentityProviderParams) (r CreateIdentityProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInstance implements createInstance operation.
//
// 在项目内注册一个数据库实例；必须标注环境。支持
// `validate_only`（测试连接，不落库）。.
//
// POST /v1/projects/{project}/instances
func (UnimplementedHandler) CreateInstance(ctx context.Context, req *CreateInstanceRequest, params CreateInstanceParams) (r CreateInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// 仅 workspaceAdmin（D1/D15）。.
//
// POST /v1/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *CreateProjectRequest, params CreateProjectParams) (r CreateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// 仅 workspaceAdmin。kind=user。.
//
// POST /v1/users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserRequest, params CreateUserParams) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorksheet implements createWorksheet operation.
//
// 保存的查询；可见性 PRIVATE/PROJECT（分享只传递 SQL 文本，D18/D36）。.
//
// POST /v1/projects/{project}/worksheets
func (UnimplementedHandler) CreateWorksheet(ctx context.Context, req *Worksheet, params CreateWorksheetParams) (r CreateWorksheetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDataSource implements deleteDataSource operation.
//
// 删除数据源.
//
// DELETE /v1/projects/{project}/instances/{instance}/dataSources/{dataSource}
func (UnimplementedHandler) DeleteDataSource(ctx context.Context, params DeleteDataSourceParams) (r DeleteDataSourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironment implements deleteEnvironment operation.
//
// 被实例引用时阻塞（409）。.
//
// DELETE /v1/environments/{environment}
func (UnimplementedHandler) DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (r DeleteEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGroup implements deleteGroup operation.
//
// 历史 IAM 绑定 `group:x@` 保留（永不命中，D31）。.
//
// DELETE /v1/groups/{group}
func (UnimplementedHandler) DeleteGroup(ctx context.Context, params DeleteGroupParams) (r DeleteGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteIdentityProvider implements deleteIdentityProvider operation.
//
// 删除 IdP.
//
// DELETE /v1/identityProviders/{idp}
func (UnimplementedHandler) DeleteIdentityProvider(ctx context.Context, params DeleteIdentityProviderParams) (r DeleteIdentityProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteInstance implements deleteInstance operation.
//
// 删除实例（软删）.
//
// DELETE /v1/projects/{project}/instances/{instance}
func (UnimplementedHandler) DeleteInstance(ctx context.Context, params DeleteInstanceParams) (r DeleteInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProject implements deleteProject operation.
//
// 非空阻塞；显式 `force=true` 才级联软删（D27）。.
//
// DELETE /v1/projects/{project}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) (r DeleteProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// 默认禁用（status=disabled）；worksheet 保留为孤儿（creator 标已禁用）。.
//
// DELETE /v1/users/{user}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorksheet implements deleteWorksheet operation.
//
// 删除 Worksheet（soft）.
//
// DELETE /v1/projects/{project}/worksheets/{worksheet}
func (UnimplementedHandler) DeleteWorksheet(ctx context.Context, params DeleteWorksheetParams) (r DeleteWorksheetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadExportTask implements downloadExportTask operation.
//
// 校验用户自设 ZIP 密码；错误 → `403 EXPORT_PASSWORD_INVALID`。 产物过期已清理
// → `404 EXPORT_ARCHIVE_EXPIRED`。下载流式解密下发。.
//
// POST /v1/projects/{project}/exportTasks/{task}:download
func (UnimplementedHandler) DownloadExportTask(ctx context.Context, req *DownloadExportRequest, params DownloadExportTaskParams) (r DownloadExportTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportAuditLogs implements exportAuditLogs operation.
//
// 按检索条件导出（CSV/JSON），返回字节流。审计的审计（x-audit:true）。.
//
// POST /v1/auditLogs:export
func (UnimplementedHandler) ExportAuditLogs(ctx context.Context, req *SearchAuditLogsRequest, params ExportAuditLogsParams) (r ExportAuditLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FavoriteWorksheet implements favoriteWorksheet operation.
//
// 收藏 Worksheet.
//
// POST /v1/projects/{project}/worksheets/{worksheet}:favorite
func (UnimplementedHandler) FavoriteWorksheet(ctx context.Context, params FavoriteWorksheetParams) (r FavoriteWorksheetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatabase implements getDatabase operation.
//
// 含 `effective_environment`（数据库未显式标注环境时继承实例环境）。.
//
// GET /v1/projects/{project}/instances/{instance}/databases/{database}
func (UnimplementedHandler) GetDatabase(ctx context.Context, params GetDatabaseParams) (r GetDatabaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironmentPolicy implements getEnvironmentPolicy operation.
//
// 查询/导出护栏（行数上限等运行时策略）。.
//
// GET /v1/environments/{environment}/policy
func (UnimplementedHandler) GetEnvironmentPolicy(ctx context.Context, params GetEnvironmentPolicyParams) (r GetEnvironmentPolicyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExportTask implements getExportTask operation.
//
// 查询任务状态、行数、产物引用等。.
//
// GET /v1/projects/{project}/exportTasks/{task}
func (UnimplementedHandler) GetExportTask(ctx context.Context, params GetExportTaskParams) (r GetExportTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroup implements getGroup operation.
//
// 获取用户组.
//
// GET /v1/groups/{group}
func (UnimplementedHandler) GetGroup(ctx context.Context, params GetGroupParams) (r GetGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIamPolicy implements getIamPolicy operation.
//
// 作用于任意资源（`projects/{p}` 或具体实例/库）。`resource`
// 在请求体传递（资源名含 `/`）。 仅 v1 预置角色；绑定含结构化条件。.
//
// POST /v1/iam:getIamPolicy
func (UnimplementedHandler) GetIamPolicy(ctx context.Context, req *GetIamPolicyRequest) (r GetIamPolicyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIdentityProvider implements getIdentityProvider operation.
//
// 获取 IdP.
//
// GET /v1/identityProviders/{idp}
func (UnimplementedHandler) GetIdentityProvider(ctx context.Context, params GetIdentityProviderParams) (r GetIdentityProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInstance implements getInstance operation.
//
// 获取实例.
//
// GET /v1/projects/{project}/instances/{instance}
func (UnimplementedHandler) GetInstance(ctx context.Context, params GetInstanceParams) (r GetInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// 获取项目.
//
// GET /v1/projects/{project}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r GetProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSetting implements getSetting operation.
//
// 读取平台设置.
//
// GET /v1/settings/{key}
func (UnimplementedHandler) GetSetting(ctx context.Context, params GetSettingParams) (r GetSettingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUnreadNotificationCount implements getUnreadNotificationCount operation.
//
// 未读通知计数.
//
// GET /v1/users/me/notifications:unreadCount
func (UnimplementedHandler) GetUnreadNotificationCount(ctx context.Context) (r GetUnreadNotificationCountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// 获取用户.
//
// GET /v1/users/{user}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorksheet implements getWorksheet operation.
//
// 获取 Worksheet.
//
// GET /v1/projects/{project}/worksheets/{worksheet}
func (UnimplementedHandler) GetWorksheet(ctx context.Context, params GetWorksheetParams) (r GetWorksheetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// 进程存活探针，不做就绪判定，不依赖下游。.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r HealthzOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatabases implements listDatabases operation.
//
// 返回实例内调用者可见的逻辑库（鉴权过滤）。.
//
// GET /v1/projects/{project}/instances/{instance}/databases
func (UnimplementedHandler) ListDatabases(ctx context.Context, params ListDatabasesParams) (r ListDatabasesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEnvironments implements listEnvironments operation.
//
// 供前端渲染环境标签与策略下拉。.
//
// GET /v1/environments
func (UnimplementedHandler) ListEnvironments(ctx context.Context) (r ListEnvironmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListExportTasks implements listExportTasks operation.
//
// 返回项目内调用者可见的导出任务（鉴权过滤）。.
//
// GET /v1/projects/{project}/exportTasks
func (UnimplementedHandler) ListExportTasks(ctx context.Context, params ListExportTasksParams) (r ListExportTasksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGroupMembers implements listGroupMembers operation.
//
// 列出组成员.
//
// GET /v1/groups/{group}/members
func (UnimplementedHandler) ListGroupMembers(ctx context.Context, params ListGroupMembersParams) (r ListGroupMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGroups implements listGroups operation.
//
// 列出用户组.
//
// GET /v1/groups
func (UnimplementedHandler) ListGroups(ctx context.Context, params ListGroupsParams) (r ListGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListIdentityProviders implements listIdentityProviders operation.
//
// 登录页渲染 SSO 按钮可匿名读取（仅返回 enabled +
// title/type/domain，不含密钥）。.
//
// GET /v1/identityProviders
func (UnimplementedHandler) ListIdentityProviders(ctx context.Context) (r ListIdentityProvidersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInstances implements listInstances operation.
//
// 返回项目内调用者可见的实例（鉴权过滤）。.
//
// GET /v1/projects/{project}/instances
func (UnimplementedHandler) ListInstances(ctx context.Context, params ListInstancesParams) (r ListInstancesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMyFavorites implements listMyFavorites operation.
//
// 当前用户的收藏书签（指向 worksheet）。.
//
// GET /v1/users/me/favorites
func (UnimplementedHandler) ListMyFavorites(ctx context.Context, params ListMyFavoritesParams) (r ListMyFavoritesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMyNotifications implements listMyNotifications operation.
//
// 我的站内通知.
//
// GET /v1/users/me/notifications
func (UnimplementedHandler) ListMyNotifications(ctx context.Context, params ListMyNotificationsParams) (r ListMyNotificationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements listProjects operation.
//
// 仅返回调用者所属项目（鉴权过滤；workspaceAdmin/securityAdmin 可见全部）。.
//
// GET /v1/projects
func (UnimplementedHandler) ListProjects(ctx context.Context, params ListProjectsParams) (r ListProjectsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// 列出用户.
//
// GET /v1/users
func (UnimplementedHandler) ListUsers(ctx context.Context, params ListUsersParams) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MarkAllNotificationsRead implements markAllNotificationsRead operation.
//
// 全部标记已读.
//
// POST /v1/users/me/notifications:markAllRead
func (UnimplementedHandler) MarkAllNotificationsRead(ctx context.Context, params MarkAllNotificationsReadParams) (r MarkAllNotificationsReadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MarkNotificationRead implements markNotificationRead operation.
//
// 标记单条已读.
//
// POST /v1/users/me/notifications/{id}:markRead
func (UnimplementedHandler) MarkNotificationRead(ctx context.Context, params MarkNotificationReadParams) (r MarkNotificationReadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// QueryHistoriesSearch implements queryHistoriesSearch operation.
//
// 仅返回调用者本人的查询/导出历史（按归属判定，非 ACL）。.
//
// GET /v1/queryHistories:search
func (UnimplementedHandler) QueryHistoriesSearch(ctx context.Context, params QueryHistoriesSearchParams) (r QueryHistoriesSearchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Readyz implements readyz operation.
//
// 校验平台元数据库连通性，可承接流量时返回 ready。.
//
// GET /readyz
func (UnimplementedHandler) Readyz(ctx context.Context) (r ReadyzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegenerateMyMfa implements regenerateMyMfa operation.
//
// 重新生成 TOTP secret（应用层加密）与恢复码，返回一次性置顶信息。.
//
// POST /v1/users/me:mfa:regenerate
func (UnimplementedHandler) RegenerateMyMfa(ctx context.Context, params RegenerateMyMfaParams) (r RegenerateMyMfaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveGroupMember implements removeGroupMember operation.
//
// 移除组成员.
//
// DELETE /v1/groups/{group}/members/{member}
func (UnimplementedHandler) RemoveGroupMember(ctx context.Context, params RemoveGroupMemberParams) (r RemoveGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchAuditLogs implements searchAuditLogs operation.
//
// 结构化过滤（method/user/resource/severity/create_time）。 `parent` = `projects/{p}`
// 走项目级读权限（projectOwner 可读本项目，D26）； 省略 `parent`
// 为全局（securityAdmin / workspaceAdmin）。大表分页上限 5000，可不返回 total_size。.
//
// POST /v1/auditLogs:search
func (UnimplementedHandler) SearchAuditLogs(ctx context.Context, req *SearchAuditLogsRequest) (r SearchAuditLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchWorksheets implements searchWorksheets operation.
//
// 返回项目内调用者可见的 worksheet（可见性 + 归属）。.
//
// GET /v1/projects/{project}/worksheets:search
func (UnimplementedHandler) SearchWorksheets(ctx context.Context, params SearchWorksheetsParams) (r SearchWorksheetsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetIamPolicy implements setIamPolicy operation.
//
// 乐观锁：请求带 `etag`，服务端不匹配 → `409 CONCURRENT_MODIFICATION`。
// 审计记录变更前后差异（service_data）。.
//
// POST /v1/iam:setIamPolicy
func (UnimplementedHandler) SetIamPolicy(ctx context.Context, req *SetIamPolicyRequest, params SetIamPolicyParams) (r SetIamPolicyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SqlExport implements sqlExport operation.
//
// 小结果集同步导出，返回用户自设密码加密的 ZIP 字节流。 预估 >1
// 万行（EXPLAIN 估算，见 D22）→ `412 EXPORT_TOO_LARGE_FOR_SYNC`，改走异步 ExportTask。.
//
// POST /v1/projects/{project}/instances/{instance}/databases/{database}:export
func (UnimplementedHandler) SqlExport(ctx context.Context, req *ExportRequest, params SqlExportParams) (r SqlExportRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SqlQuery implements sqlQuery operation.
//
// 核心查询路径。多语句（分号分隔）首请求执行全部语句，响应 `results[]`
// 按序返回每条语句的首页； 取某结果集下一页 → 带 `page_token` 再次 POST
// `:query`（此时 `statement` 忽略，服务端按 token 续读）。
// 只读强制；语句超时、行数/字节上限按环境策略 `environment_policies` 生效。.
//
// POST /v1/projects/{project}/instances/{instance}/databases/{database}:query
func (UnimplementedHandler) SqlQuery(ctx context.Context, req *QueryRequest, params SqlQueryParams) (r SqlQueryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncDatabaseSchema implements syncDatabaseSchema operation.
//
// 即时返回 202 + 当前 sync_status；后台异步反射 schema 写入快照（D41）。.
//
// POST /v1/projects/{project}/instances/{instance}/databases/{database}:syncSchema
func (UnimplementedHandler) SyncDatabaseSchema(ctx context.Context, params SyncDatabaseSchemaParams) (r SyncDatabaseSchemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncInstance implements syncInstance operation.
//
// 即时返回 202 + 当前 `sync_status` + 触发时间；后台异步执行（D41）。 完成后写
// `last_sync_time`/`sync_status`，可选推站内通知。不引入 LRO 轮询。.
//
// POST /v1/projects/{project}/instances/{instance}:sync
func (UnimplementedHandler) SyncInstance(ctx context.Context, params SyncInstanceParams) (r SyncInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestIamPermissions implements testIamPermissions operation.
//
// 按调用者本人对 `resource` 持有的权限判定，返回命中的权限子集（用于前端
// UI 收敛）。.
//
// POST /v1/iam:testIamPermissions
func (UnimplementedHandler) TestIamPermissions(ctx context.Context, req *TestIamPermissionsRequest) (r TestIamPermissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestIdentityProvider implements testIdentityProvider operation.
//
// 以授权码测试连通性，返回 `IdentityProviderUserInfo`（不落库）。.
//
// POST /v1/identityProviders/{idp}:test
func (UnimplementedHandler) TestIdentityProvider(ctx context.Context, req *TestIdentityProviderRequest, params TestIdentityProviderParams) (r TestIdentityProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestInstanceConnection implements testInstanceConnection operation.
//
// 以请求体中的数据源凭据尝试连接（`validate_only` 语义），不落库。.
//
// POST /v1/projects/{project}/instances/{instance}:testConnection
func (UnimplementedHandler) TestInstanceConnection(ctx context.Context, req *TestConnectionRequest, params TestInstanceConnectionParams) (r TestInstanceConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UndeleteProject implements undeleteProject operation.
//
// 恢复已删除项目.
//
// POST /v1/projects/{project}:undelete
func (UnimplementedHandler) UndeleteProject(ctx context.Context, params UndeleteProjectParams) (r UndeleteProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UndeleteUser implements undeleteUser operation.
//
// 恢复用户.
//
// POST /v1/users/{user}:undelete
func (UnimplementedHandler) UndeleteUser(ctx context.Context, params UndeleteUserParams) (r UndeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnfavoriteWorksheet implements unfavoriteWorksheet operation.
//
// 取消收藏 Worksheet.
//
// POST /v1/projects/{project}/worksheets/{worksheet}:unfavorite
func (UnimplementedHandler) UnfavoriteWorksheet(ctx context.Context, params UnfavoriteWorksheetParams) (r UnfavoriteWorksheetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDataSource implements updateDataSource operation.
//
// 更新数据源.
//
// PATCH /v1/projects/{project}/instances/{instance}/dataSources/{dataSource}
func (UnimplementedHandler) UpdateDataSource(ctx context.Context, req *DataSource, params UpdateDataSourceParams) (r UpdateDataSourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDatabase implements updateDatabase operation.
//
// 更新数据库（标签/显示设置）.
//
// PATCH /v1/projects/{project}/instances/{instance}/databases/{database}
func (UnimplementedHandler) UpdateDatabase(ctx context.Context, req *Database, params UpdateDatabaseParams) (r UpdateDatabaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEnvironment implements updateEnvironment operation.
//
// 更新环境.
//
// PATCH /v1/environments/{environment}
func (UnimplementedHandler) UpdateEnvironment(ctx context.Context, req *Environment, params UpdateEnvironmentParams) (r UpdateEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEnvironmentPolicy implements updateEnvironmentPolicy operation.
//
// 仅 securityAdmin/workspaceAdmin；记审计前值。.
//
// PATCH /v1/environments/{environment}/policy
func (UnimplementedHandler) UpdateEnvironmentPolicy(ctx context.Context, req *EnvironmentPolicy, params UpdateEnvironmentPolicyParams) (r UpdateEnvironmentPolicyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGroup implements updateGroup operation.
//
// 更新用户组.
//
// PATCH /v1/groups/{group}
func (UnimplementedHandler) UpdateGroup(ctx context.Context, req *Group, params UpdateGroupParams) (r UpdateGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIdentityProvider implements updateIdentityProvider operation.
//
// 更新 IdP.
//
// PATCH /v1/identityProviders/{idp}
func (UnimplementedHandler) UpdateIdentityProvider(ctx context.Context, req *IdentityProvider, params UpdateIdentityProviderParams) (r UpdateIdentityProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateInstance implements updateInstance operation.
//
// PATCH + JSON Merge Patch；可改展示名、同步间隔、设置等。.
//
// PATCH /v1/projects/{project}/instances/{instance}
func (UnimplementedHandler) UpdateInstance(ctx context.Context, req *Instance, params UpdateInstanceParams) (r UpdateInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// 更新项目.
//
// PATCH /v1/projects/{project}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *Project, params UpdateProjectParams) (r UpdateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSetting implements updateSetting operation.
//
// 仅 workspaceAdmin/securityAdmin；记审计前值。.
//
// PATCH /v1/settings/{key}
func (UnimplementedHandler) UpdateSetting(ctx context.Context, req *Setting, params UpdateSettingParams) (r UpdateSettingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements updateUser operation.
//
// 更新用户.
//
// PATCH /v1/users/{user}
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *User, params UpdateUserParams) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorksheet implements updateWorksheet operation.
//
// 乐观锁；`If-Match: <etag>`，不匹配 → `409 CONCURRENT_MODIFICATION`。.
//
// PATCH /v1/projects/{project}/worksheets/{worksheet}
func (UnimplementedHandler) UpdateWorksheet(ctx context.Context, req *Worksheet, params UpdateWorksheetParams) (r UpdateWorksheetRes, _ error) {
	return r, ht.ErrNotImplemented
}
